[project]
name="agents-at-work"
version = "0.1.0"
description = "Agents at Work - Podcast"
readme = "README.md"
requires-python=">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "claudette>=0.1.6",
    "ipykernel>=6.29.5",
    "nbdev>=2.4.2",
    "youtube-transcript-api>=1.0.3",
]
